name: craigslist_vehicle_project
version: "1.0.0"

config-version: 2

profile: craigslist_vehicle_project

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  craigslist_vehicle_project:
    staging:
      +materialized: view

    marts:
      +materialized: table